name: Commit Message Check
on: [pull_request]
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: wagoid/commitlint-github-action@v5
      with:
        configFile: .commitlintrc.json